// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: pinecone/storage.proto

package pinecone

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// Represents a single record (row) in the vector database in the storage (i.e. at rest)
type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// The ID of the record.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//*
	// The namespace of for record.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	//*
	// The vector data
	VectorData *NdArray `protobuf:"bytes,3,opt,name=vector_data,json=vectorData,proto3" json:"vector_data,omitempty"`
	//*
	// The metadata encoded as a string.
	MetadataString string `protobuf:"bytes,4,opt,name=metadata_string,json=metadataString,proto3" json:"metadata_string,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pinecone_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_pinecone_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_pinecone_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Record) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Record) GetVectorData() *NdArray {
	if x != nil {
		return x.VectorData
	}
	return nil
}

func (x *Record) GetMetadataString() string {
	if x != nil {
		return x.MetadataString
	}
	return ""
}

type LogReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Reference:
	//	*LogReference_Kafka
	Reference isLogReference_Reference `protobuf_oneof:"reference"`
}

func (x *LogReference) Reset() {
	*x = LogReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pinecone_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogReference) ProtoMessage() {}

func (x *LogReference) ProtoReflect() protoreflect.Message {
	mi := &file_pinecone_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogReference.ProtoReflect.Descriptor instead.
func (*LogReference) Descriptor() ([]byte, []int) {
	return file_pinecone_storage_proto_rawDescGZIP(), []int{1}
}

func (m *LogReference) GetReference() isLogReference_Reference {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (x *LogReference) GetKafka() *KafkaLogReference {
	if x, ok := x.GetReference().(*LogReference_Kafka); ok {
		return x.Kafka
	}
	return nil
}

type isLogReference_Reference interface {
	isLogReference_Reference()
}

type LogReference_Kafka struct {
	Kafka *KafkaLogReference `protobuf:"bytes,1,opt,name=kafka,proto3,oneof"`
}

func (*LogReference_Kafka) isLogReference_Reference() {}

type KafkaLogReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BootstrapServer string `protobuf:"bytes,1,opt,name=bootstrap_server,json=bootstrapServer,proto3" json:"bootstrap_server,omitempty"`
	Partition       int32  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset          int64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *KafkaLogReference) Reset() {
	*x = KafkaLogReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pinecone_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KafkaLogReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaLogReference) ProtoMessage() {}

func (x *KafkaLogReference) ProtoReflect() protoreflect.Message {
	mi := &file_pinecone_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaLogReference.ProtoReflect.Descriptor instead.
func (*KafkaLogReference) Descriptor() ([]byte, []int) {
	return file_pinecone_storage_proto_rawDescGZIP(), []int{2}
}

func (x *KafkaLogReference) GetBootstrapServer() string {
	if x != nil {
		return x.BootstrapServer
	}
	return ""
}

func (x *KafkaLogReference) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *KafkaLogReference) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_pinecone_storage_proto protoreflect.FileDescriptor

var file_pinecone_storage_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x69, 0x6e, 0x65, 0x63, 0x6f, 0x6e, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x13,
	0x70, 0x69, 0x6e, 0x65, 0x63, 0x6f, 0x6e, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x0b,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x64, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x52, 0x0a, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x0f,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x4c, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4b, 0x61, 0x66, 0x6b,
	0x61, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x42, 0x0b, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x22, 0x74, 0x0a, 0x11, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x62, 0x6f, 0x6f, 0x74,
	0x73, 0x74, 0x72, 0x61, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x40, 0x0a, 0x11, 0x69, 0x6f, 0x2e,
	0x70, 0x69, 0x6e, 0x65, 0x63, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x2b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x6e, 0x65, 0x63,
	0x6f, 0x6e, 0x65, 0x2d, 0x69, 0x6f, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x69, 0x6e, 0x65, 0x63, 0x6f,
	0x6e, 0x65, 0x2f, 0x70, 0x69, 0x6e, 0x65, 0x63, 0x6f, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pinecone_storage_proto_rawDescOnce sync.Once
	file_pinecone_storage_proto_rawDescData = file_pinecone_storage_proto_rawDesc
)

func file_pinecone_storage_proto_rawDescGZIP() []byte {
	file_pinecone_storage_proto_rawDescOnce.Do(func() {
		file_pinecone_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_pinecone_storage_proto_rawDescData)
	})
	return file_pinecone_storage_proto_rawDescData
}

var file_pinecone_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pinecone_storage_proto_goTypes = []interface{}{
	(*Record)(nil),            // 0: core.Record
	(*LogReference)(nil),      // 1: core.LogReference
	(*KafkaLogReference)(nil), // 2: core.KafkaLogReference
	(*NdArray)(nil),           // 3: core.NdArray
}
var file_pinecone_storage_proto_depIdxs = []int32{
	3, // 0: core.Record.vector_data:type_name -> core.NdArray
	2, // 1: core.LogReference.kafka:type_name -> core.KafkaLogReference
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pinecone_storage_proto_init() }
func file_pinecone_storage_proto_init() {
	if File_pinecone_storage_proto != nil {
		return
	}
	file_pinecone_core_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pinecone_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pinecone_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pinecone_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KafkaLogReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pinecone_storage_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*LogReference_Kafka)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pinecone_storage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pinecone_storage_proto_goTypes,
		DependencyIndexes: file_pinecone_storage_proto_depIdxs,
		MessageInfos:      file_pinecone_storage_proto_msgTypes,
	}.Build()
	File_pinecone_storage_proto = out.File
	file_pinecone_storage_proto_rawDesc = nil
	file_pinecone_storage_proto_goTypes = nil
	file_pinecone_storage_proto_depIdxs = nil
}
