name: 'Build client documentation'
description: 'Generates client documentation using godoc'
runs:
  using: 'composite'
  steps:
    - name: Write html file to docs directory
      run: |
        @godoc -url pkg/github.com/pinecone-io/go-pinecone/pinecone/ > ../../../docs/godoc-documentation.html
      shell: bash