name: 'Generate client documentation'
description: 'Generates client documentation using godoc'

runs:
  using: 'composite'
  steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Run gopages to generate documentation
      shell: bash
      run: |
        gopages
